# Generated by Django 5.0.6 on 2026-06-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('role', models.CharField(choices=[('barber', 'Barber'), ('nail_tech', 'Nail Technician'), ('both', 'Barber & Nail Tech'), ('manager', 'Manager')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specializations', models.ManyToManyField(blank=True, related_name='stylists', to='services.servicecategory')),
            ],
            options={
                'ordering': ['order', 'first_name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='team_stylis_is_acti_e883aa_idx')],
            },
        ),
    ]
